# compose-ubuntu.yml

version: '2.1'

services:

  ubuntu-service:

    image: ubuntu

    volumes:
      - ${DISK}/BLOCK/test:/test
      
    command: tail -F /dev/null

# docker run -it ubuntu bash
# docker exec -it "composename" bash
