# compose-simnet.yml

#docker run \
#--shm-size=1g \
#--ulimit memlock=-1 \
#--ulimit stack=67108864 \
#--runtime nvidia \
#-v ${PWD}/examples:/examples \
#-it simnet:21.06 bash

version: '2.1'

services:

  simnet-service:

    shm_size: '1g'

    ulimits:
      memlock: '-1'
      stack: '67108864'

    volumes:
      - /mnt/103bae77-3b0b-4bdd-8573-d2c5b8734ab5/BLOCK/SimNet/examples:/examples
      #- $(readlink -f ${HOME}/BLOCK/)/SimNet/examples:/examples
      #- ${BLOCK}/SimNet/examples:/examples
      - ${HOME}/Docker/volume-simnet:/home/volume-simnet

    runtime: 'nvidia'

    image: "simnet:21.06"

    command: tail -F /dev/null
    
# docker exec -i -t "composename" bash
